    name: GitHub Classroom Workflow

    on: [pull_request]

    jobs:
      build:
        name: Autograding
        strategy:
          fail-fast: false
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: ocaml/setup-ocaml@v2
            with:
              ocaml-compiler: 4.12.0
              dune-cache: true
          - uses: education/autograding@v1
